### PR TITLE
Support for Spigot 1.13 API changes

### PR DESCRIPTION
**Pull request by kickash32**
Built and tested changes on Spigot 1.13.2. It seems to run as intended without any issues or errors.

### CODE REVIEW

**Comment by StargateMC** [comment]
Wow thanks @kickash32 ! Have you tested this on previous versions? Can I grab a copy of the JAR as well? I don't code much anymore, but it'd be cool to release a 3.3.1 :) Much appreciated!

**Comment by kickash32** [comment]
I haven't tested it in previous versions. I actually just started coding spigot plugins so I don't know if it will work or not. I have a compiled jar, but I forgot to increase the version number (also its pretty fat). If you want I can put it up as a release on my fork.

**Comment by StargateMC** [comment]
Sounds good! I'll make sure the code works on older versions and do a new release here when I have some time with credit to you for the help.

**Comment by kickash32** [comment]
Done! Good luck testing, let me know If you run into any problems.

**Pull request merged**
